#some python magic here, the unittest2 runner fails because it can't import the test_utils
import test_utils